### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- Upgrade to wordpress 4.8
- Using the last helpers
- Following the new example app
- Fix issues https://github.com/YunoHost-Apps/wordpress_ynh/issues/24 and https://github.com/YunoHost-Apps/wordpress_ynh/issues/21

## Solution
- Change the upstream version
- Force language with wp-cli
- Force upgrade important plugins
- Force auto-upgrade with a simple plugin, and allow each user to manage their upgrades.

## PR Status
Could be reviewed and tested.

## Validation
---
*Medium decision*
- [ ] **Complete test** : 
- [ ] **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- [ ] **CI succeeded** : 
- [ ] **CI succeeded** : 
One public package check log is enough instead of two checks.  
When the PR is mark as ready to merge, you have to wait for 7 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
We have no bad returns from this testing branch.
So let's review it.

@YunoHost-Apps/apps-group

**Review by JimboJoe — APPROVED** [review]

**Comment by JimboJoe** [comment]
I agree to yolomerge as the reviews have been made and I don't think we have availability to make more tests (hence testing branches...).
I'm also in favor of yolomerging other official testing branches for the same reason and because I understand we're loosing more time in support telling there are testing branches than debugging potential remaining bugs after merging. ...

**Pull request merged**
