### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *No changelog*
- *Change `is_public` was not working as expected*
- *No actions and config_panel yet*
- *Php is configured with a default config*
- *App not up to date*
- *wp-fail2ban plugin is becoming a premium plugin with a recurrent ads about going to the premium version. And the main dev of this plugin seems to not care about it.*

## Solution
- *Add a changelog*
- *`is_public` is either 1 or 0 (not true of false)*
- *Add an action for public/private and a config-panel*
- *Use ynh_get_scalable_phpfpm to set php according to the ram, cpu and expected usage.*
- *Update to 5.4*
- *Remove wp-fail2ban and replace it by wp-fail2ban-redux.*
- *Fix buster install*
- *Add 3 new actions to reset the app*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR85/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready for review

**Review by kay0u — DISMISSED** [review]
LGTM & code review

**Comment by lapineige** [comment]
I did my upgrade using `yunohost app upgrade wordpress -u https://github.com/YunoHost-Apps/wordpress_ynh` yet I'm still in 5.3.2 🤔

**Comment by maniackcrudelis** [comment]
@lapineige for wordpress, the upgrade of the package does not upgrade the app itself.
That's for 3 reasons
  - Wordpress is quite a sensitive app regarding security, and so I don't want to upgrade the app only on an upgrade of the package.
  - Wordpress can upgrade itself from its admin panel. Thus, an upgrade from the package could end up with a downgrade, which would probably have some consequences on the database and the plugins.
  - This package add a plugin to auto-upgrade wordpress, and so wordpress *is supposed to* be up to date.

**Comment by lapineige** [comment]
Ok, I was confused by the "Upgrade to 5.4" message in PR.
Yes it updates itself automatically in my case, for minor versions I'm sure, for majors ones I don't remember… And I was not in 5.4.
And upgrade fails… I'll investigate.
Thanks :)

**Comment by maniackcrudelis** [comment]
Interested by the result of you investigations, that plugin seems capricious...

**Comment by lapineige** [comment]
Well on the web some people said it could be a memory limit, I changed the value in `/etc/php/7.0/fpm/conf.d/20-wordpress.ini` and restarted php7.0 but nothing changed.

I tried with the us_US version, it worked, and apart from the "what's new" page, everything is still in French :thinking:

**Comment by maniackcrudelis** [comment]
Ok, so actually the plugin did its job, but the upgrade failed ?
I know also that the fr version can fail to upgrade. Don't know why though.

**Comment by lapineige** [comment]
I guess so… I didn't check the logs.

**Comment by maniackcrudelis** [comment]
Just check my main wordpress, only the upgrade to 5.4 wasn't done.
Maybe as the major version it's not done automatically.

**Comment by lapineige** [comment]
The plugin says that it should upgrade major versions too.
It's probably just that major upgrade that failed :thinking:

**Review by kay0u — DISMISSED** [review]
LGTM & code review :rocket:

Thank you for the great work

**Comment by kay0u** [comment]
> I did my upgrade using `yunohost app upgrade wordpress -u https://github.com/YunoHost-Apps/wordpress_ynh` yet I'm still in 5.3.2 thinking

pleas upgrade with:
 `yunohost app upgrade wordpress -u https://github.com/YunoHost-Apps/wordpress_ynh/tree/testing` (with **/tree/testing** at the end)

**Comment by lapineige** [comment]
So it's needed, even if testing is the base branch right now ?

**Comment by kay0u** [comment]
https://github.com/YunoHost/yunohost/blob/dd0f3cd78418f7d1932ae3a122755b3e522e3df5/src/yunohost/app.py#L2106-L2110

It seems that, if no `/tree/branchname` is provided, then we use `master` by default :-)

**Comment by lapineige** [comment]
It worked :)

**Comment by maniackcrudelis** [comment]
Will be merged in 3 days (finally !)

**Comment by lapineige** [comment]
Auto-update to 5.4.1 worked, maybe it was only v5.4 that was complicated for some reason…

**Comment by kay0u** [comment]
https://wordpress.org/support/article/configuring-automatic-background-updates/#core-updates

> By default, every site has automatic updates enabled for minor core releases and translation files. [...]

Not for major one :-)

**Comment by maniackcrudelis** [comment]
Same for me, got my update to 5.4.1 yesterday for one of my wordpress.

@kay0u, the package adds a plugin that is supposed to auto update.
But this plugin seems to work only when it feels like it...

**Comment by kay0u** [comment]
> Same for me, got my update to 5.4.1 yesterday for one of my wordpress.
> 
> @kay0u, the package adds a plugin that is supposed to auto update.
> But this plugin seems to work only when it feels like it...

According to this [doc](https://wordpress.org/support/article/configuring-automatic-background-updates/#constant-to-configure-core-updates)
We can set `WP_AUTO_UPDATE_CORE` to `true` (`minor` by default) to allow major update, but is it something we really want to do?

**Comment by maniackcrudelis** [comment]
To auto upgrade yes.
But that's not only the core, but also the plugins and themes. Probably even more dangerous than the core itself.

Anyway, the most important I think is that an user can upgrade as soon as he has a update available. And if it can be done before he even notice it, that's even better.

**Comment by lapineige** [comment]
Considering Wordpress (core+plugins+themes) risks regarding security, I'm also for an automatic update of everything, by default. I think it's worth keeping their Wordpress as secure as possible, with the (still limited) risk of breaking their install (while they may have backups) or going into maintenance mode, instead of relying on every admin and user to stay informed about new updates (for every major/minor release, and plugin/theme update) and make the updates in time and taking the risk that their Wordpress or Yunohost server is compromised.

It's easy to disable that plug-in (yet we might advertise that feature in the readme, for those whiling to disable this) if people want to do that by hand.

For my part sometime I see updates for >10 plugins in one day, and several times a week. That would be a pain to maintain everything up-to-date manually.

**Comment by lapineige** [comment]
> But this plugin seems to work only when it feels like it...

I just did a fresh install : in fact by default it is (now ?) configured not to auto upgrade for major versions.

**Pull request merged**
