### PR TITLE
6.0 Bullseye

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 6.0
#156
#114

- To be merged after Bullseye release

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@tituspijean testing with wordpress 5.9.3, PHP8.0 and with you PR #158. Seems to fix the #156 issue.
Question à mille francs. How is WordPress updated in the upgrade script? 

Edit. I found the answer in the email sent to admin after install

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!bullseyetestme

**Review by yalh76 — CHANGES_REQUESTED** [review]
Not a good idea to go to a major version 6.0
And they recommand PHP7.4 or greater, so going to 7.4 is better than going directly to 8.0
And will be better to definitely fix #156 before going to a big new version

**Pull request closed without merging**
