### PR TITLE
Level 6

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Level 6*

## Solution

- *Try to fix it*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by alexAubin** [comment]
>Config/panel (actions):       fail

[...]

```
TypeError: hook_exec() got an unexpected keyword argument 'user'
```

Actions are broken in 4.2 unfortunately, so we either gotta fix the core, or disable the action test for now (Eric G had a similar story iirc)

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> Actions are broken in 4.2 unfortunately, so we either gotta fix the core, or disable the action test for now (Eric G had a similar story iirc)

Disabling action test for now ^^

**Pull request merged**
