### PR TITLE
Upgrade to Wordpress 5.2

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Upgrade aren't automatic if the instance isn't public or often visited.*

- *Not up to date..*

## Solution
- *Force a visit everyday with a cron to trig the automatic updater*

- *Upgrade to wordpress 5.2*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR63/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by lapineige** [comment]
This cron is a very good idea, thanks @maniackcrudelis ! :slightly_smiling_face:

**Comment by maniackcrudelis** [comment]
Thanks @lapineige, but that wasn't my idea, https://wordpress.org/support/topic/does-not-upgrade/#post-11384024

**Comment by lapineige** [comment]
Still, thanks for the implementation ;)

**Review by kay0u — APPROVED** [review]
LGTM & code review

**Review by JimboJoe — APPROVED** [review]
LGTM :+1:

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
