### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *New version upstream*

## Solution
- *Upgrade to version 5.6*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR116/)  

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by yalh76 — DISMISSED** [review]

**Comment by tituspijean** [comment]
I get a regression from the [package checker](https://paste.yunohost.org/raw/zibovevage), confirmed by installing the PR, for the private install test:  `App is not private: it should redirect to the Yunohost portal, but is publicly accessible instead`.

**Comment by ericgaspar** [comment]
> I get a regression from the [package checker](https://paste.yunohost.org/raw/zibovevage), confirmed by installing the PR, for the private install test: `App is not private: it should redirect to the Yunohost portal, but is publicly accessible instead`.

Should be solved by 54007e6

**Comment by tituspijean** [comment]
[Solved, indeed!](https://paste.yunohost.org/raw/xaxuxerewa)

**Review by tituspijean — APPROVED** [review]

**Review by yalh76 — APPROVED** [review]
Quick review, LGTM

**Review by alexAubin — APPROVED** [review]
LGTM

**Pull request merged**
