### PR TITLE
Upgrade to v6.0.3 and fix auto-updater

### PR DESCRIPTION
**Pull request by tituspijean**
## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
> WARNING Multisite option of WordPress doesn't work at the root of a domain.

I don't understand this warning/error. It looks like the `check_process` file is not properly read?

**Comment by yalh76** [comment]
> > WARNING Multisite option of WordPress doesn't work at the root of a domain.
> 
> I don't understand this warning/error. It looks like the `check_process` file is not properly read?

Should be because of https://github.com/YunoHost/package_check/pull/125

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> > WARNING Multisite option of WordPress doesn't work at the root of a domain.
> 
> I don't understand this warning/error. It looks like the `check_process` file is not properly read?

seems specific to ci-apps-dev :/

not having it on the ci-apps nor manual package_check

**Comment by yalh76** [comment]
@tituspijean seems resolved, I don't know how ...

**Review by ericgaspar — APPROVED** [review]

**Pull request merged**
