### PR TITLE
Add action and config-panel feature

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *No actions and config_panel yet*

## Solution
- *Add an action for public/private and a config-panel*

Replace #47

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR79/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by kay0u — DISMISSED** [review]
LGTM & code review

Keep in mind that as soon as Yunohost 3.7 is released, `is_public` will be obsolete.

**Comment by maniackcrudelis** [comment]
Still waiting for a proper documentation about it...
Last time I asked for it, I didn't have any answer.

Breaking apps without warning doesn't feel like a good idea to me.
And meanwhile, that's still the way to handle is_public.

**Comment by kay0u** [comment]
You can find a doc [here](https://github.com/YunoHost/doc/blob/group-and-permissions/groups_and_permissions.md)

**Comment by maniackcrudelis** [comment]
as I already explained [here](https://forum.yunohost.org/t/yunohost-3-7-spooky-testing-call-for-feedback/9385/31), just saying "there's a new way to do it, the old way won't work anymore" isn't a good way to handle that.
We have apps that **NEED** to modify the settings, so those apps should be able to do it.

I asked for a clear explanation with examples to help packagers to modify their apps, this isn't an explanation about how to migrate, https://github.com/YunoHost/doc/blob/group-and-permissions/groups_and_permissions.md#migrating-away-from-the-legacy-permission-management
This is just, "the new way is better, get rid of the old crap and everything will be wonderful". What are we !? A modern democracy that decide what's better and let people struggle with the shit !!!?

I we can't deliver a proper migration process, we probably should not change that permission system !
And I clearly have no time myself to try to figure out all of that to explain to others packagers how to do it.

@Psycojoker @alexAubin @Josue-T

**Review by JimboJoe — DISMISSED** [review]
LGTM :+1:

**Pull request merged**
