### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *If the app is private, the http request for cron fails*

## Solution
- *Update link to multisite glossary*
- *Fix cron*
- *Add php7.3-ldap as dependency required by the ldap plugin*
- *Add a message about major versions of Wordpress: Fix https://github.com/YunoHost-Apps/wordpress_ynh/issues/124*
- *Upgrade to 5.7*
- *Use new permission system: Fix https://github.com/YunoHost-Apps/wordpress_ynh/issues/98 Fix https://github.com/YunoHost-Apps/wordpress_ynh/issues/107*
- *Fix config file permission: Fix https://github.com/YunoHost-Apps/wordpress_ynh/issues/122*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by yalh76 — DISMISSED** [review]
Quick review, LGTM

**Review by yalh76 — DISMISSED** [review]

**Review by yalh76 — DISMISSED** [review]

**Comment by kay0u** [comment]
!testme

**Review by yalh76 — DISMISSED** [review]

**Review by alexAubin — DISMISSED** [review]
Super quick review, LGTM but didn't look deeper into the sql stuff

**Comment by alexAubin** [comment]
𝖘𝖒𝖔𝖑 𝖇𝖚𝖒𝖕

**Comment by kay0u** [comment]
Yeah, in fact, Idk what to do with this note: https://github.com/YunoHost-Apps/wordpress_ynh/issues/124

**Comment by alexAubin** [comment]
Ugh yeah I wasnt aware of this, dunno how to handle it either ... I guess personally I too find it a bit weird to have major upgrades being applied automagically (but in doubt I would stick to "what people usually do in the wordpress community / or what's the recommendation" (if there's any, idk))

I'm not too shocked about the version number in ynh not being in sync with the actual running version ... (in fact we have similar issues for other packages installed from a debian package so we don't really control the upgrade process)

**Comment by kay0u** [comment]
> (but in doubt I would stick to "what people usually do in the wordpress community / or what's the recommendation" (if there's any, idk))

I'm not a big user of Wordpress, so I don't really know what the community recommend about upgrades

**Review by yalh76 — DISMISSED** [review]

**Comment by kay0u** [comment]
!testme

**Comment by lapineige** [comment]
Ready to merge ?

**Review by yalh76 — APPROVED** [review]
Quick review, LGTM

**Pull request merged**
