### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 6.0.1
- Upgrade to PHP8.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Review by tituspijean — APPROVED** [review]
Quick test, LGTM.

**Comment by tituspijean** [comment]
Oh sorry. I use a browser extension for Github that has the feature to auto-delete branches after merges... and I had the tab still opened. I will disable that. (https://github.com/refined-github/refined-github/issues/5868)

**Comment by yalh76** [comment]
> Oh sorry. I use a browser extension for Github that has the feature to auto-delete branches after merges... and I had the tab still opened. I will disable that.

no problems ^^

**Pull request merged**
