### PR TITLE
6.0.1

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to 6.0.1
- Upgrade to PHP8.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
