### PR TITLE
Testing

### LINKED ISSUE #156: Accessing uploaded files broken since PR 155
### Describe the bug

With [PR 155](https://github.com/YunoHost-Apps/wordpress_ynh/pull/155) media upload is broken due to problems with access rights.
Files uploaded will be properly uploaded to the server, thumbnails are created properly, but the new files are not accessible. Preview images stay empty.

When installing last version before PR 155 (https://github.com/YunoHost-Apps/wordpress_ynh/commit/e0c54b84abc3719d83a3f2fda243e690760270a6) file upload works as expected.

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH && through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: https://github.com/YunoHost-Apps/wordpress_ynh/commit/a42dbf35fde78effd3513fc0c734f78e7457dcca
- If upgrading, current package version: 5.8~ynh1

### Steps to reproduce

- ```sh
    sudo yunohost app install wordpress
    ```
- In WP Admin panel `https://<hidden>/wptest/wp-admin/`
   1. Navigate to media (`wptest/wp-admin/upload.php`)
   2. Click on button "Add New"
   3. Select and upload any image file from your local system
   4. Watch progress bar complete
   5. Observe blank preview image
   6. Developer tools reveal response status 404 from server
   7. checking nginx error logs show
       ```plain
          2022/03/21 07:22:05 [crit] 9807#9807: *1993 stat() "/var/www/wordpress__4/wp-content/uploads/2022/03/noisehd-300x169.png" failed (13: Permission denied), client: <hidden>, server: <hidden>, request: "GET /wptest/wp-content/uploads/2022/03/noisehd-300x169.png HTTP/2.0", host: "<hidden>", referrer: "https://<hidden>/wptest/wp-admin/upload.php"
       ```

### Expected behavior

Access rights should be granted in a way that the serving process is able to read uploaded files.

### Logs

https://paste.yunohost.org/raw/tafuvogoyi

### Screenshot

image

### PR DESCRIPTION
**Pull request by ericgaspar**
- Closes https://github.com/YunoHost-Apps/wordpress_ynh/issues/156, hopefully.**
   **https://github.com/YunoHost-Apps/wordpress_ynh/pull/155 seems to have introduced a regression in the files ownership, preventing users from uploading media.
This PR makes sure all files and directories belong to $app:$app, in accordance with the [PHP configuration](https://github.com/YunoHost/yunohost/blob/981fca64e234848510a2daeafec1eda07516e0ac/data/helpers.d/php#L156-L157), and set ACLs to still allow www-data to read most of the files (except wp-config.php)
- Upgrade to [5.9.3](https://github.com/YunoHost-Apps/wordpress_ynh/pull/165/commits/1a2b9252361a85f19c86ff0bc545f8fbcb6c5f2c)
- Deactivate `config_panel.toml`

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by jakobkilian** [comment]
I did a fresh install with `sudo yunohost app install https://github.com/YunoHost-Apps/wordpress_ynh/tree/testing --debug` which should include this merge (right?). I still have the same issue: 

```
-rw-r----- 1 wordpress www-data   45194 May 24 12:13 new-upload-150x150.png
-rw-r----- 1 wordpress wordpress 159554 May 24 12:13 new-upload.png
```

Should I test sth else for you?

**Comment by ericgaspar** [comment]
@tituspijean What about merging this PR that fixes the permission issue for uploaded images (although not completely [cf. comment](https://github.com/YunoHost-Apps/wordpress_ynh/pull/165#issuecomment-1135866336)), so we can move forward and find a more definitive fix?

Edit: @kay0u Do you have any clues to this issue #156?

**Comment by tituspijean** [comment]
Let's upgrade yes, even though the fix is not working yet. :)

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
