### PR TITLE
Explanation about updates of wordpress core.

### PR DESCRIPTION
**Pull request by Thatoo**
## Problem
It was unclear that updates needed to be done from inside wordpress admin panel. Other yunohost packages are all updated from yunohost admin panel.

## Solution
Write an explanation to invite admins to keep their wordpress updated by updating their wordpress blog from inside the wordpress admin panel and not wait that it is offered in the yunohost admin panel (as I was doing till today :-)

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wordpress_ynh%20-BRANCH-%20(Official)/) *Please replace '-BRANCH-' in this link for a PR from a local branch.*  
or  
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wordpress_ynh%20PR-NUM-%20(Official_fork)/) *Replace '-NUM-' by the PR number in this link for a PR from a forked repository.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
This package actually adds [Companion auto update](https://wordpress.org/plugins/companion-auto-update) to wordpress to have automatic updates.
You're not supposed to update manually your wordpress.
But the reality is indeed that this plugin seems sometime (often?) capricious.

It would be better to find a solution to fix that behavior instead of asking to admin to update manually.

**Comment by Thatoo** [comment]
You're right, that would be better. In the meantime, a small explanation could be useful I think. This is only my modest point of view of course.

**Comment by maniackcrudelis** [comment]
I don't know when I will have time to investigate, so in the meantime it could be useful indeed.

Could you though please move that comment into the "Limitation" part and add an explanation that this is temporary because the plug-in isn't working as expected.

**Comment by Thatoo** [comment]
I moved it into "Limitation" and I tried to be as clear as possible. I hope it's not too long.

**Review by maniackcrudelis — APPROVED** [review]

**Comment by maniackcrudelis** [comment]
Merged as a micro decision, only a change into the readme

**Pull request merged**
