### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *No changelog*

## Solution
- *Add a changelog*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR82/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by kay0u — APPROVED** [review]
LGTM & code review

**Comment by maniackcrudelis** [comment]
up

**Review by JimboJoe — APPROVED** [review]
LGTM :+1:

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
