### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *The upgrade process fails if http-authentication is network activated*
- *Issue alias_[traversal](https://github.com/yandex/gixy/blob/master/docs/en/plugins/aliastraversal.md)*
- *Update to last standart*

## Solution
- *Desactive the plugin even if it can be network activated.*
- *Fix the issue by adding a rewrite and a final slash on location.*
- *Upgrade to 4.9.1*
- *Add a change_url script*
- *Add fail2ban*
- *Add ynh_abort_if_up_to_date*
- *Add ynh_send_readme_to_admin*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : Verified by the CI.
- [x] **Code review** : JimboJoe from #38, #39, #41
- [x] **Approval (LGTM)** : JimboJoe from #38, #39, #41
- [X] **Approval (LGTM)** : frju365 
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wordpress_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Ready to be review, just a LGTM missing.

**Comment by alexAubin** [comment]
(I spent way too much time making this)

ezgif-5-a2085414a9

**Comment by frju365** [comment]
In fact, if you wait for reviewers, I suggestion you next time to add app_group as reviewer :P

**Review by frju365 — APPROVED** [review]
LGTM

**Comment by frju365** [comment]
Will be merged in 3 days as requested !

**Comment by alexAubin** [comment]
Let's meeeeeeeeerge /o/

**Pull request merged**
