### PR TITLE
Fix_http2_support

### PR DESCRIPTION
**Pull request by Josue-T**
## Problem
- The wordpress installation fail if http2 is enabled on nginx

## Solution
- As discuted [here](https://forum.yunohost.org/t/yunohost-3-http2/5590/14?u=josue_t) just add a `sleep 2`

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/wordpress_ynh%20Fix_http2_support%20(Official)/) 

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
As it's a fix about curl, it would be better to add it in the helper, and not here.

**Comment by Josue-T** [comment]
It's a relation about the "nginx reload" called just before. Yes we can do this, but in this case it could be good to add the nginx reload too in the helper.

**Comment by maniackcrudelis** [comment]
Before YNH_CURL became the official helper ynh_local_curl, it has a sleep.
As you can see here, https://github.com/YunoHost-Apps/wordpress_ynh/commit/c8e6bce9c90a3120ff87ceb2eb9cf4b722307fef#diff-dc2801cb46a5d60e62234cff98084498L102

This sleep has fix a lot of error, especially with /etc/hosts.
I think we can simply re-add it to the current helper to prevent any further errors in other apps than this one.

**Comment by Josue-T** [comment]
I've made a PR in the core [here](https://github.com/YunoHost/yunohost/pull/547)

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/YunoHost/yunohost/pull/547

**Pull request closed without merging**
